# Generated by Django 3.2.5 on 2021-07-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('bik', models.CharField(max_length=9, verbose_name='Бик')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('account', models.CharField(max_length=20, verbose_name='Счет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('review', models.TextField(verbose_name='Отзыв о банке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_db.bank')),
            ],
        ),
    ]
