# Generated by Django 3.2.5 on 2021-07-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='bank',
            name='account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
    ]
