# Generated by Django 3.2.5 on 2021-07-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_db', '0002_auto_20210712_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
